language: python
python:
  - "2.7"

before_install:
  - nvm install 7.4.0
  - nvm use 7.4.0

install:
  - npm install
  - node_modules/.bin/node-sass --include-path node_modules static/sass --output static/css
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8 requests[security]
  - pip install https://github.com/nottrobin/linkchecker/archive/fix-install.zip

before_script:
  - python manage.py runserver &

script:
  - flake8 webapp
  - sleep 2 && linkchecker --threads 2 --ignore-url /usn --no-warnings http://127.0.0.1:8000

